name: build/deploy osparc-python-runner

on: ["push", "pull_request"]

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: building osparc-python-runner
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.9"]
        os: [ubuntu-22.04]
        node: [10]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: ${{ matrix.docker_buildx }}
          driver: docker
      - name: setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v3
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: set owner variable
        run: echo "OWNER=${GITHUB_REPOSITORY%/*}" >> $GITHUB_ENV
      - name: set docker image tag
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF##*/}-${{ matrix.python }}" >> $GITHUB_ENV
      - name: set dev environs
        run: make devenv
      - name: get current image if available
        run: make pull-latest || true
      - name: build
        run: |
          make build-x
          make info-build
      - name: test
        run: make tests
      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: deploy
        run: |
          ./ci/helpers/dockerhub_login.bash
          make push
      - if: github.event_name == 'push' && github.ref != 'refs/heads/master'
        name: deploy
        run: |
          ./ci/helpers/dockerhub_login.bash
          make push-version

